package lock

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type BundleEntry struct {
	ID          string    `json:"id"`
	Source      string    `json:"source"`
	Version     string    `json:"version"`
	Hash        string    `json:"hash"`
	InstalledAt time.Time `json:"installed_at"`
}

type Lockfile struct {
	Version int           `json:"version"`
	Bundles []BundleEntry `json:"bundles"`
}

func (lf *Lockfile) Upsert(entry BundleEntry) {
	for i, b := range lf.Bundles {
		if b.ID == entry.ID {
			lf.Bundles[i] = entry
			return
		}
	}
	lf.Bundles = append(lf.Bundles, entry)
}

func (lf *Lockfile) Remove(id string) bool {
	for i, b := range lf.Bundles {
		if b.ID == id {
			lf.Bundles = append(lf.Bundles[:i], lf.Bundles[i+1:]...)
			return true
		}
	}
	return false
}

func ReadLockfile(path string) (*Lockfile, error) {
	cleanPath := filepath.Clean(path)
	// #nosec G304 -- lockfile path is provided by caller or default workspace okf.lock
	f, err := os.Open(cleanPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &Lockfile{Version: 1}, nil
		}
		return nil, err
	}
	defer func() { _ = f.Close() }()

	lf := &Lockfile{Version: 1}
	scanner := bufio.NewScanner(f)
	var current *BundleEntry

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "version:") {
			_, _ = fmt.Sscanf(line, "version: %d", &lf.Version)
			continue
		}
		if strings.HasPrefix(line, "- id:") {
			if current != nil {
				lf.Bundles = append(lf.Bundles, *current)
			}
			val := strings.TrimSpace(strings.TrimPrefix(line, "- id:"))
			val = strings.Trim(val, `"'`)
			current = &BundleEntry{ID: val}
			continue
		}
		if current != nil {
			parts := strings.SplitN(line, ":", 2)
			if len(parts) == 2 {
				k := strings.TrimSpace(parts[0])
				v := strings.Trim(strings.TrimSpace(parts[1]), `"'`)
				switch k {
				case "source":
					current.Source = v
				case "version":
					current.Version = v
				case "hash":
					current.Hash = v
				case "installed_at":
					t, _ := time.Parse(time.RFC3339, v)
					current.InstalledAt = t
				}
			}
		}
	}
	if current != nil {
		lf.Bundles = append(lf.Bundles, *current)
	}

	return lf, scanner.Err()
}

func WriteLockfile(path string, lf *Lockfile) error {
	cleanPath := filepath.Clean(path)
	// #nosec G304 -- lockfile path is provided by caller or default workspace okf.lock
	f, err := os.Create(cleanPath)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	w := bufio.NewWriter(f)
	if _, err := fmt.Fprintf(w, "# okf.lock - Generated by OKF Agent Memory. DO NOT EDIT MANUALLY.\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "version: %d\n", lf.Version); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "bundles:\n"); err != nil {
		return err
	}
	for _, b := range lf.Bundles {
		if _, err := fmt.Fprintf(w, "  - id: %q\n", b.ID); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "    source: %q\n", b.Source); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "    version: %q\n", b.Version); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "    hash: %q\n", b.Hash); err != nil {
			return err
		}
		if _, err := fmt.Fprintf(w, "    installed_at: %q\n", b.InstalledAt.UTC().Format(time.RFC3339)); err != nil {
			return err
		}
	}
	return w.Flush()
}
